#! /bin/sh

# $1 = Directory to operate on
# $2 = Hashing executable
# $3 = Verbosity
##Empty = Critical output only
##Nonempty = Flavor text

hashProgram=$2

if [ -z "${1}" ]; then echo "No directory input"; exit 1; fi
if [ -z "${hashProgram}" ]; then hashProgram="sha1sum"; fi
if [ -n "${3}" ]; then echo "Directory:"  $1; echo "Hash program:" $hashProgram; fi

# Piping strategy from:
# https://stackoverflow.com/questions/545387/linux-compute-a-single-hash-for-a-given-folder-contents/545413#545413

hashes=$(find $1 -type f -print0 | sort -z | xargs -0 $hashProgram)
files=$(find $1 \( -type f -o -type d \) -print0 | sort -z | xargs -0 stat -c '%n %a' )
echo "$hashes"
echo "$files"
echo -e "$hashes"\n"$files" | $hashProgram
